#!/bin/bash
echo "this is $0"
v=$(awk '/^Version/{print $2}' pkg/DESCRIPTION)
command="R CMD check --as-cran SoilR_${v}.tar.gz"
echo $command
eval $command

es=0
cf="SoilR.Rcheck/00check.log"
nw=$(grep -c warning $cf)
echo $nw
if [ $nw -gt 0 ]
  then 
  echo "#################################"
  echo "###### There were warnings.######"
  echo "#################################"
  echo ""
  echo "the output of R CMD check --as-cran:"
  cat $cf
  es=1
fi

exit $es
