#!/bin/bash
es=0
echo "this is $0"
for ft in ".*.Rd" "*.R" "*.Rnw" 
	do 
	files=$(find pkg|grep $ft)
	for f in $files
	do
		grep -P -n "[\x80-\xFF]" $f
		if [ $? -eq 0 ] # found something
			then es=1
			echo $f
		fi
	done
done
exit $es
