<p>                                                                                            
At the moment we use R-forge as a device to fill the gap between a package release at cran and the latest version of the project at the 
<a href="http://gauss1.igw.uni-jena.de"/>                                                      
SoilR intranet
</a>
hosted on our own server.                                                                      
</p>
<p>
 R-forge provides a good platform for this intermediate releases that are smaller than a package version but have a longer lifespan than the revisions of our mercurial repository, which is the place where the development takes place on a day to day basis. 
</p>
<p>
The mercurial repository is part of our site also contains a lot more information e.g. a       
<a href="http://gauss1.igw.uni-jena.de/trac//wiki/WikiStart"/>                                 
wiki
</a>
and                                                                                            
ticket system to which you can gain access by sending a request via email to mamueller"at" bgc-jena.mpg.de.
So please visit us on:                                                                         
</p>

<a href="http://gauss1.igw.uni-jena.de"/>                                                      
    SoilR intranet                                                                             
</a>                                                                                           
</p>
    

